spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/demo-ddd?useSSL=false&serverTimezone=GMT%2B8&characterEncoding=UTF-8&useUnicode=true&autoReconnect=true&allowMultiQueries=true&rewriteBatchedStatements=true
    username: root
    password: root
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8


## mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    jdbc-type-for-null: null
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    banner: false
    db-config:
      logic-delete-value: 'NOW()'
      logic-not-delete-value: 'NULL'